# Site settings
title_left    : "Cyber"
title_right   : "JUG" # default: ""
description   : "Die virtuelle Java User Group"
keywords      : "CyberJUG, Java User Group, virtuell, cyber, java"
url           : "https://cyberjug.de" # site url
baseurl       : "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover         : "" # image uri like logo/cover image for site seo

# google_analytics  : UA-XXXXX-XX
twitter_username  : "cyberjug"
comments_enabled  : false # if enabled (set to true), please provide your disqus_username
disqus_shortname  : ""
postshare_enabled : false

# Build settings
permalink   : /:year/:month/:day/:title/
markdown    : kramdown
highlighter : rouge

source      : ./
destination : ./docs

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : expanded

# Author settings
author:
  name     : "Die Orga der CyberJUG"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : ueber_uns
    title: Ãœber uns
  - slug : termine
    title: Termine

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md", "script", "vendor", cyberjug.gemspec]
